---
- hosts: webservers
  vars:
    ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_rsa
    ansible_user: jenkins
    ansible_become: yes
    java_packages:
      - openjdk-8-jdk
    tomcat_java_home: "/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre"

  roles:
    - role: ansible-role-tomcat8
